[project]
name = "mssql-mcp-server"
version = "0.1.0"
description = "A Model Context Protocol (MCP) server for Microsoft SQL Server integration, providing LLMs with access to database resources and SQL query execution capabilities"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mcp[cli]>=1.10.1",
    "pydantic-settings>=2.10.1",
    "pyodbc>=5.2.0",
    "sqlparse>=0.5.5",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
